---
- hosts: all
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    apps_dir: "{{ home_dir }}/Library/Application Support/"

  roles:
      - { role: basic-tools }
      - { role: comms }
      - { role: dev-tools }
      - { role: entertainment }
      - { role: git }
      - { role: lightroom }
      - { role: mac-preferences }
      - { role: productivity }
      - { role: security }