- name: check if homebrew is installed
  command: brew -V
  failed_when: no
  register: brew_check

- name: install homebrew with curl
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: brew_check.rc != -1

- name: Install Homebrew Cask using homebrew
  homebrew:
    name: cask
    state: present

- name: Tap Homebrew Cask
  command: brew tap caskroom/versions